
#if !defined(POC_DATA_MODEL_HEADER_DISABLE_DEF_UNDEF)


#undef POC_DATA_MODEL
#undef POC_DATA_MODEL_STRING

#undef POC_DATA_MODEL_UNKNOWN
#undef POC_DATA_MODEL_UNKNOWN_ID
#undef POC_DATA_MODEL_UNKNOWN_STRING

#undef POC_DATA_MODEL_LP32
#undef POC_DATA_MODEL_LP32_ID
#undef POC_DATA_MODEL_LP32_STRING

#undef POC_DATA_MODEL_ILP32
#undef POC_DATA_MODEL_ILP32_ID
#undef POC_DATA_MODEL_ILP32_STRING

#undef POC_DATA_MODEL_LP64
#undef POC_DATA_MODEL_LP64_ID
#undef POC_DATA_MODEL_LP64_STRING

#undef POC_DATA_MODEL_LLP64
#undef POC_DATA_MODEL_LLP64_ID
#undef POC_DATA_MODEL_LLP64_STRING

#undef POC_DATA_MODEL_ILP64
#undef POC_DATA_MODEL_ILP64_ID
#undef POC_DATA_MODEL_ILP64_STRING

#undef POC_DATA_MODEL_SILP64
#undef POC_DATA_MODEL_SILP64_ID
#undef POC_DATA_MODEL_SILP64_STRING



#endif // !defined(POC_DATA_MODEL_HEADER_DISABLE_DEF_UNDEF)
