
#define POC_DATA_MODEL_UNKNOWN
#define POC_DATA_MODEL_UNKNOWN_ID
#define POC_DATA_MODEL_UNKNOWN_STRING

#define POC_DATA_MODEL_LP32
#define POC_DATA_MODEL_LP32_ID
#define POC_DATA_MODEL_LP32_STRING

#define POC_DATA_MODEL_ILP32
#define POC_DATA_MODEL_ILP32_ID
#define POC_DATA_MODEL_ILP32_STRING

#define POC_DATA_MODEL_LP64
#define POC_DATA_MODEL_LP64_ID
#define POC_DATA_MODEL_LP64_STRING

#define POC_DATA_MODEL_LLP64
#define POC_DATA_MODEL_LLP64_ID
#define POC_DATA_MODEL_LLP64_STRING

#define POC_DATA_MODEL_ILP64
#define POC_DATA_MODEL_ILP64_ID
#define POC_DATA_MODEL_ILP64_STRING

#define POC_DATA_MODEL_SILP64
#define POC_DATA_MODEL_SILP64_ID
#define POC_DATA_MODEL_SILP64_STRING
