
#undef POC_ARCH_ID
#undef POC_ARCH_STRING

#undef POC_ARCH_UNKNOWN
#undef POC_ARCH_UNKNOWN_ID
#undef POC_ARCH_UNKNOWN_STRING

#undef POC_ARCH_X86
#undef POC_ARCH_X86_ID
#undef POC_ARCH_X86_STRING

#undef_POC_ARCH_X86_32
#undef_POC_ARCH_X86_32_ID
#undef_POC_ARCH_X86_32_STRING

#undef POC_ARCH_X86_64
#undef POC_ARCH_X86_64_ID
#undef POC_ARCH_X86_64_STRING

#undef POC_ARCH_PPC
#undef POC_ARCH_PPC_ID
#undef POC_ARCH_PPC_STRING

#undef_POC_ARCH_PPC64
#undef_POC_ARCH_PPC64_ID
#undef_POC_ARCH_PPC64_STRING
