
#if !defined(POC_LANG_HEADER_DISABLE_DEF_UNDEF)


#undef POC_LANG
#undef POC_LANG_STRING

#undef POC_LANG_UNKNOWN
#undef POC_LANG_UNKNOWN_ID
#undef POC_LANG_UNKNOWN_STRING

#undef POC_LANG_C
#undef POC_LANG_C_STRING

#undef POC_LANG_C_UNKNOWN_ID
#undef POC_LANG_C_UNKNOWN_STRING

#undef POC_LANG_C_C89
#undef POC_LANG_C_C89_ID
#undef POC_LANG_C_C89_STRING
#undef POC_LANG_C_C89_STANDARDIZED_VERSION


#undef POC_LANG_C_C99
#undef POC_LANG_C_C99_ID
#undef POC_LANG_C_C99_STRING
#undef POC_LANG_C_C99_STANDARDIZED_VERSION

#undef POC_LANG_CPP
#undef POC_LANG_CPP_STRING

#undef POC_LANG_CPP_UNKNOWN_ID
#undef POC_LANG_CPP_UNKNOWN_STRING

#undef POC_LANG_CPP_CPP98
#undef POC_LANG_CPP_CPP98_ID
#undef POC_LANG_CPP_CPP98_STRING
#undef POC_LANG_CPP_CPP98_STANDARDIZED_VERSION

#undef POC_LANG_OBJC
#undef POC_LANG_OBJC_ID
#undef POC_LANG_OBJC_STRING

#undef POC_LANG_OBJC_UNKNOWN_ID
#undef POC_LANG_OBJC_UNKNOWN_STRING

#undef POC_LANG_OPENCL
#undef POC_LANG_OPENCL_ID
#undef POC_LANG_OPENCL_STRING
#undef POC_LANG_OPENCL_VERSION

#undef POC_LANG_OPENCL_UNKNOWN_ID
#undef POC_LANG_OPENCL_UNKNOWN_STRING




#undef POC_LANG_C_TYPE_BOOL_SUPPORT
#undef POC_LANG_C_TYPE_LONG_LONG_SUPPORT
#undef POC_LANG_C_TYPE_LONG_DOUBLE_SUPPORT
#undef POC_LANG_C_TYPE_COMPLEX_SUPPORT
#undef POC_LANG_C_TYPE_IMAGINARY_SUPPORT
#undef POC_LANG_C_HEADER_STDBOOL_SUPPORT
#undef POC_LANG_C_HEADER_STDINT_SUPPORT



#undef POC_LANG_CPP_RTTI_SUPPORT
#undef POC_LANG_CPP_EXCEPTIONS_SUPPORT



#endif // !defined(POC_LANG_HEADER_DISABLE_DEF_UNDEF)
