
#if !defined(POC_PORTABILITY_MACROS_HEADER_DISABLE_DEF_UNDEF)


#undef POC_INLINE
#undef POC_RESTRICT
#undef POC_ALIGN_BEGIN
#undef POC_ALIGN_END


#endif // !defined(POC_PORTABILITY_MACROS_HEADER_DISABLE_DEF_UNDEF)
