
#undef POC_ENDIAN_UNKNOWN_ID
#undef POC_ENDIAN_UNKNOWN_STRING

#undef POC_ENDIAN_LITTLE
#undef POC_ENDIAN_LITTLE_ID
#undef POC_ENDIAN_LITTLE_STRING

#undef POC_ENDIAN_BIG
#undef POC_ENDIAN_BIG_ID
#undef POC_ENDIAN_BIG_STRING
